### ISSUE TITLE
po文件中的词条如果没有msgctxt, 无法被找到。

### ISSUE THREAD

**Issue by yetist** [chai2010/gettext-go#1]
在代码中：

```
gettext.Gettext("Hello world!").
```

po文件中：

```
#: main.go:19
msgid "Hello world!"
msgstr "你好世界！"
```

这种情况将无法得到翻译字符串。

看了代码，在解析mo文件并将翻译保存到dict中时，使用了msgctxt+'\004'+msgid做为key。
在有msgctxt的情况下工作很正常，如PGettext("msgctxt", "msgid")。
在无msgctxt的情况下，Gettext("msgid")无法得到翻译字符串。在dict中实际的key是msgid的内容。而Gettext函数到dict中查找翻译字符串时，以所在函数名做为msgctxt，最后形成&lt;func name&gt;+'\004'+msgid做为key来查找，结果无法找到翻译字符串。

如果Gettext()函数能生成正确的key，问题就能解决，修改方法如下：

```
diff --git a/gettext/gettext.go b/gettext/gettext.go
index ca14065..2171c74 100644
--- a/gettext/gettext.go
+++ b/gettext/gettext.go
@@ -80,7 +80,7 @@ func Textdomain(domain string) string {
 //     msg := gettext.Gettext("Hello") // msgctxt is "some/package/name.Foo"
 // }
 func Gettext(msgid string) string {
-   return PGettext(callerName(2), msgid)
+   return PGettext("", msgid)
 }

 // Getdata attempt to translate a resource file into the user's native language,
```

**Comment by chai2010** [comment]
感谢你的反馈.

关于这个问题, `Gettext` 默认是启用了 `callerName` 作为 `context`.
如果是这样改的话, 虽然可以回避这个问题, 但是函数的行为也发生了改变.

我个人感觉更好的方式是用 `gettext.PGettext("", msgid)` 手工指定 `context`.

更本质的问题是, 这个 `po` 文件是从哪里来的?
如果是针对 `gettext-go` 生成的, 那么 `context` 一般是必须的.
如果是其他的工具生成的, 那可能就要麻烦很多了.

**Comment by yetist** [comment]
是的，本质问题是po文件如何生成的。
我的测试代码如下，gettext.Gettext等相关函数被封装成了__, N_,C_,NC_,Q_等便利函数(参考了glib)。
```
func main() {
	BindTextdomain(PkgName, "locale", nil)
	Textdomain(PkgName)
	SetLocale("zh_CN")

	fmt.Printf("__:%s\n", __("Hello world!"))
	fmt.Printf("N_:%s, %s\n", PkgName, __(PkgName))
	fmt.Printf("NC_(n.):%s, %s\n", nWord, C_("n.", "Chinese"))
	fmt.Printf("NC_(a.):%s, %s\n", aWord, C_("a.", "Chinese"))
	fmt.Printf("C_:%s\n", NC_("main", "CHello world!"))
	fmt.Printf("Q_:%s\n", Q_("main|QHello world!"))
}
```
po文件使用xgettext工具生成，生成过程如下:
```
#!/bin/bash
LANGS=('en_US' 'zh_CN' 'zh_TW')
DOMAIN=example
SOURCES=*.go
KEYWORDS="--keyword=__ --keyword=N_ --keyword=C_:1c,2 --keyword=NC_:1c,2 --keyword=Q_:1g"
xgettext -d $DOMAIN -s $SOURCES -o ${DOMAIN}.pot -L c++ -i $KEYWORDS
for l in ${LANGS[@]}; do
	[ -d locale/$l/LC_MESSAGES ] || mkdir -p locale/$l/LC_MESSAGES
	if [ -f locale/$l/LC_MESSAGES/${DOMAIN}.po ]; then
		msgmerge -U locale/$l/LC_MESSAGES/${DOMAIN}.po ${DOMAIN}.pot
	else
		msginit -l ${l}.utf8 -o locale/$l/LC_MESSAGES/${DOMAIN}.po -i ${DOMAIN}.pot
	fi
	msgfmt -c -v -o  locale/$l/LC_MESSAGES/${DOMAIN}.mo locale/$l/LC_MESSAGES/${DOMAIN}.po
done
```
生成的pot文件内容：
```
#: main.go:23 main.go:32
msgctxt "main"
msgid   "CHello world!"
msgstr  ""

#: main.go:10 main.go:22 main.go:31
msgctxt "a."
msgid   "Chinese"
msgstr  ""

#: main.go:9 main.go:21 main.go:30
msgctxt "n."
msgid   "Chinese"
msgstr  ""

#: main.go:19 main.go:28
msgid   "Hello world!"
msgstr  ""

#: main.go:24 main.go:33
msgctxt "main"
msgid   "QHello world!"
msgstr  ""

#: main.go:8
msgid   "example"
msgstr  ""
```

注意其中的"Hello world!"和"example"两个词条，这里不会生成msgctxt上下文，这个行为是正确的。

目前，我可以在自己封装的__()函数中，使用gettext.PGettext("", msgid)来使用，但还是希望能直接从库中修复这个问题。

**Comment by yetist** [comment]
特别的，你提到：
>如果是针对 gettext-go 生成的, 那么 context 一般是必须的.
>如果是其他的工具生成的, 那可能就要麻烦很多了.

gettext做为一种通用的国际化语言解决方案，gettext-go做为golang对gettext的支持，不应该对所使用的po/mo文件有特殊的要求，因为这会破坏其通用性。
在linux中，大部分的/usr/share/locale/*/LC_MESSAGES/*mo文件都不使用msgctxt上下文，而它们仍然正常工作。使用context上下文只是其中很特殊的个别情况：
```
$msgunfmt /usr/share/locale/zh_CN/LC_MESSAGES/*mo 2>/dev/null|grep msgid|wc
   6318   28694  190550
$msgunfmt /usr/share/locale/zh_CN/LC_MESSAGES/*mo 2>/dev/null|grep msgctxt|wc
     29      86     613
```

**Comment by chai2010** [comment]
根本问题在于目前 `gettext-go` 还缺乏一个类似 `xgettext` 的工具.
而标准的 `xgettext` 其实并不支持 Go 语言(很多用法是为了迁就C/C++语言).

关于`context`的问题, 其实标准的`gettext`没有`context`用法并不好, 因为很容易出现重名但是意思不同的翻译.
`gettext-go`其实是参考了一部分Qt的设计, Qt中 `tr` 默认的`context`是当前的class(好像是).
`context`结合Go语言特有的`caller`信息算是比较完美的解决方式了.

而且, `gettext-go`最开始的目标其实想用用来提前godoc的文档, 然后用poedit之类的工具翻译.
翻译完成后再用程序进行自动合并...

可惜工具的缺乏是`gettext-go`目前比较短板的地方.

PS: 你有没有兴趣帮忙整一个类似`xgettext`的工具?

这里有一个类似的例子:
https://github.com/lxn/polyglot/blob/master/polyglot/main.go

**Comment by yetist** [comment]
考虑过这个问题没有：
如果每一个相同的词条(指msgid相同，msgstr也相同)，由于在源文件的不同函数中，那么生成的po文件会由于context的不同而产生多个词条，这些词条实际上是重复的。而在没有context的情况下，它们会自动合并，只产生一个词条。

**Comment by yetist** [comment]
对于这个目标：
>而且, gettext-go最开始的目标其实想用用来提前godoc的文档, 然后用poedit之类的工具翻译.
>翻译完成后再用程序进行自动合并...

解决问题的办法不应该由gettext-go来提供，这两者的目标完全不同。

为解决源码内嵌文档的翻译，需要专用程序来完成po的生成和翻译的合并，不需要编译成mo文件。

在生成po时，增加特殊的标识用来标识此段文档在源码中的位置信息。在合并时，读取此标识并将翻译合并到源码中。

这有一个类似的例子，是使用po文件来翻译gtkdoc文档的：
https://code.google.com/p/gtk-doc-cn/

**Comment by chai2010** [comment]
是会出现多个text要翻译(Qt中应该是这样).

如果没有`context`的, 自动合并的text, 一般会加上 `fuzzy` 标签.
`fuzzy`标签是需要翻译者手工修改的(不然就不会被提取到mo文件).

**Comment by chai2010** [comment]
感谢提供gtkdoc的链接, 我要先了解下这个.

**Comment by siongui** [comment]
這個issue能否在README或documentation裡提一下，像我用Python的gettext也不需要msgctxt就可以找到，剛剛寫了個程式測一下，一直沒辦法翻譯，好在看到這個issue討論串才解決，要不是我看得懂中文，真的不知道該如何解決，請 @chai2010 能把這個issue跟workaround寫進README方便非中文使用者。

**Comment by chai2010** [comment]
v1.0.0 开始 `Gettext` 默认采用空字符串作为 `msgctxt`
