### ISSUE TITLE
Need multiple languages support for multiple threads

### ISSUE THREAD

**Issue by JiangtianLi** [chai2010/gettext-go#8]
One scenario is for serving web requests with different languages. It seems domainManager is not exported and only defaultDomainManager can be used. It would be nice to export domainManager or have some way to allow different  clients/threads to have different domainManger with its own locale.

**Comment by chai2010** [comment]
fixed in https://github.com/chai2010/gettext-go/releases/tag/v1.0.0-alpha.0

```go
	zh := gettext.New("hello", "./examples/locale").SetLanguage("zh_CN")
	fmt.Println(zh.Gettext("Hello, world!"))

	en := gettext.New("hello", "./examples/locale").SetLanguage("en")
	fmt.Println(en.Gettext("Hello, world!"))
```
